### ISSUE TITLE
Update "Red" Color in Repo

### ISSUE THREAD

**Issue by samureiser** [wuben2602/tddtnews#17]
Thank you, Ben, for putting this together!

I would like to request that you replace `#c42e38` with `#ff0f0f` in 

- emailcreator/templates/parts/event.jinja and 
- emailcreator/templates/parts/news.jinja 

so that the shade of red in the newsletter matches the shade of red on https://www.tddt.org/

Thanks! Maybe I'll have an opportunity to give your code a closer look at some point!

**Comment by wuben2602** [comment]
fixed in commit 9c41059fca844ef6a51ea1fcfac85e5ab7d15e14
